/**
 * @Description: 公共json key
 * @Author:      zhz
 * @Version:     1
 */

#ifndef SRC_LIB_NET_SERVER_BASE_JKEY_COMMON_H_
#define SRC_LIB_NET_SERVER_BASE_JKEY_COMMON_H_

#define JKEY_ID                  "id"
#define JKEY_FROM                "from"
#define JKEY_FROM_NAME           "from_name"
#define JKEY_TO_NAME             "to_name"
#define JKEY_TYPE                "type"
#define JKEY_CONTENT             "content"
 
#define JKEY_SSID                "ssid"
#define JKEY_PASSWORD            "password"
#define JKEY_TIMEZONE            "timezone"
#define JKEY_TIME                "time"
 
#define JKEY_VERSION             "version"
#define JKEY_MAC                 "mac"
#define JKEY_SN                  "sn"
 
#define JKEY_BODY                "body"
#define JKEY_GEAR                "gear"
#define JKEY_STATUS              "status"
#define JKEY_MAP                 "map"
#define JKEY_MAP_ID              "map_id"
#define JKEY_MAP_NAME            "map_name"
#define JKEY_MAP_INFO_PATH       "map_info_path"
#define JKEY_MAP_DATA_PATH       "map_data_path"
#define JKEY_RESOLUTION          "resolution"
#define JKEY_WIDTH               "width"
#define JKEY_HEIGHT              "height"
#define JKEY_X_MIN               "x_min"
#define JKEY_Y_MIN               "y_min"
#define JKEY_MAP_ORIGINAL_SIZE   "map_original_size"
#define JKEY_MODE                "mode"
#define JKEY_VOLUME              "volume"
#define JKEY_ENABLE              "enable"
#define JKEY_GUID                "guid"
#define JKEY_PACK_NUM            "pack_num"
#define JKEY_SUB_NUM             "sub_num"
 
#define JKEY_BRAKE               "brake"
#define JKEY_V                   "v"
#define JKEY_W                   "w"
#define JKEY_CTRL                "ctrl"
#define JKEY_ORIENT              "orient"
#define JKEY_DIS                 "dis"
 
#define JKEY_X_ACCEL             "x_accel"
#define JKEY_Y_ACCEL             "y_accel"
#define JKEY_Z_ACCEL             "z_accel"
#define JKEY_X_GYRO              "x_gyro"
#define JKEY_Y_GYRO              "y_gyro"
#define JKEY_Z_GYRO              "z_gyro"
#define JKEY_COURSE_ANGLE        "course_angle"
#define JKEY_RUG                 "rug"
#define JKEY_COLLISION           "collision"
#define JKEY_COLLISION_LF        "collision_lf"
#define JKEY_COLLISION_LB        "collision_lb"
#define JKEY_COLLISION_RF        "collision_rf"
#define JKEY_COLLISION_RB        "collision_rb"
#define JKEY_GNDDET_LF           "gnddet_lf"
#define JKEY_GNDDET_LB           "gnddet_lb"
#define JKEY_GNDDET_RF           "gnddet_rf"
#define JKEY_GNDDET_RB           "gnddet_rb"
#define JKEY_ELECTRIC_QY         "electric_qy"
#define JKEY_WHEEL_L_CURR        "wheel_l_curr"
#define JKEY_WHEEL_R_CURR        "wheel_r_curr"
#define JKEY_FAN_CURR            "fan_curr"
#define JKEY_MID_CURR            "mid_curr"
#define JKEY_SIDE_L_CURR         "side_l_curr"
#define JKEY_SIDE_R_CURR         "side_r_curr"
#define JKEY_MOP_CURR            "mop_curr"
#define JKEY_FAN_CURR            "fan_curr"
#define JKEY_ODM_LEFT            "odm_left"
#define JKEY_ODM_RIGHT           "odm_right"
#define JKEY_ODM_V               "odm_v"
#define JKEY_ODM_W               "odm_w"
#define JKEY_ABNORMAL            "abnormal"
#define JKEY_BATTERY_LEVEL       "battery_level"
#define JKEY_ALARM               "alarm"
#define JKEY_VL6180              "vl6180"
#define JKEY_IMU                 "imu"
#define JKEY_BATTERY             "battery"
#define JKEY_GND_DET             "gnd-det"
#define JKEY_CURRENT             "current"
#define JKEY_ODM                 "odm"
#define JKEY_LEVEL               "level"
#define JKEY_VL53L5CX            "vl53l5cx"
#define JKEY_DATA                "data"
 
#define JKEY_AREA                "area"
#define JKEY_TIME                "time"
 
#define JKEY_TRACK_X             "track_x"
#define JKEY_TRACK_Y             "track_y"
#define JKEY_LOG                 "log"
 
#define JKEY_ROBOT_TRAJ          "robot_traj"
#define JKEY_DEVICE_STATE        "device_state"
#define JKEY_CLEAN_STATE         "clean_state"
#define JKEY_LASER_POSE          "laser_pose"
#define JKEY_ASTAR               "astar"
#define JKEY_COVER               "cover"
#define JKEY_STATE               "state"
 
#define JKEY_FORCE_TIME          "force_time"
#define JKEY_TIME_ZONE           "time_zone"
 
#define JKEY_NAME                "name"
#define JKEY_ROOM                "room"
 
#define JKEY_CLEAN_AREA          "clean_area"
#define JKEY_CLEAN_TIME          "clean_time"
#define JKEY_CLEAN_MODE          "clean_mode"
#define JKEY_CLEAN_STRENGTH      "clean_strength"
#define JKEY_AUDIO               "audio"
#define JKEY_DONOT_DISTURB       "donot_disturb"
#define JKEY_TIMING_CLEAN        "timing_clean"
#define JKEY_SELF_CLEAN          "self_clean"
#define JKEY_SELF_CLEAN_PROGRESS "self_clean_progress"
#define JKEY_CLEAN_ROBOT_POS     "clean_robot_pos"
#define JKEY_CHARGE_BASE_POS     "charge_base_pos"
#define JKEY_CURRENT_MAP_ID      "current_map_id"

#define JKEY_DEV_TIME            "dev_time"
#define JKEY_ACTIVATE            "activate"
#define JKEY_DEVICE              "device"
#define JKEY_SW_VERSION          "sw_version"
#define JKEY_HW_VERSION          "hw_version"
#define JKEY_HWVER               "hwver"
#define JKEY_SWVER               "swver"
#define JKEY_CODE                "code"
#define JKEY_START_POS           "start_pos"
#define JKEY_URL                 "url"
#define JKEY_VOICE_TTS           "voice_tts"
#define JKEY_BUTTONS             "buttons"
#define JKEY_WIFI_STATE          "wifi_state"

#define JKEY_MAIN_FAULT          "main_fault"
#define JKEY_BASE_FAULT          "base_fault"


#endif