/**
 * @Description: 公共宏和结构体
 * @Author:      zhz
 * @Version:     1
 */

#ifndef SRC_LIB_SCHEDULE_SERVER_BASE_COMMON_H_
#define SRC_LIB_SCHEDULE_SERVER_BASE_COMMON_H_

#define DP_SCHEDULE_REQUEST           "DP_SCHEDULE_REQUEST" //netserver 发的请求
#define DP_SCHEDULE_BROADCAST         "DP_SCHEDULE_BROADCAST" //schedule发送的广播
#define DP_PERIPHERALS_REQUEST        "DP_PERIPHERALS_REQUEST" //发给PERIPHERALS请求
#define DP_PERIPHERALS_BROADCAST      "DP_PERIPHERALS_BROADCAST" //PERIPHERALS发的广播
#define DP_DB_BROADCAST      "DP_DB_BROADCAST"
#define DP_DB_REQUEST        "DP_DB_REQUEST" //发给PERIPHERALS请求

#endif